services:
  frontend:
    build:
      context: .
      dockerfile: ./containers/frontend/Dockerfile
    image: app:v0.0.0
    volumes:
      - ./frontend:/app
    ports:
      - "5173:5173"
    command: pnpm dev --host